### ISSUE TITLE
onEnter do not fire when I click enter/return

### ISSUE THREAD

**Issue by rosa-nugget** [curvenote/prosemirror-autocomplete#11]
I have a function linked to onEnter and nothing is happening when I press the return key. I found out onEnter is just being called  for the tab key.

I am on a Macbook I am not sure if that change something.

Here the configuration I have.

 optionsAutocomplete: Partial<Options> = {
    triggers: [
      {
        name: 'variable',
        trigger: '/'
      },
    ],
    onOpen: ({ view, range, trigger, type }) =>
      this.handleOpen({ view, range, trigger, type }),
    onArrow: ({ view, kind }) => this.handleArrow({ view, kind }),
    onFilter: ({ view, filter }) => this.handleFilter({ view, filter }),
    onEnter: ({ view }) => this.handleSelect({ view }),
    onClose: ({ view }) => this.handleClose({ view }),
  };

**Comment by rosa-nugget** [comment]
I found out why it was not working , it is not related with the prosemirror-autocomplete plugin, I have another plugin that is overriding the keybiding. Thanks

**Comment by rowanc1** [comment]
Glad you got it sorted!
